### ISSUE TITLE
request: more info in tooltip

### ISSUE THREAD

**Issue by kowach** [alex2108/syncthing-tray#18]
It would be nice to have more info in icon tooltip text like
- current Download/Upload Rate
- Last File Received per device
- syncing errors

**Comment by alex2108** [comment]
sry for the late reply, definately makes sense and I will see what I can do.

One problem is that I noticed the text does not update at all on Ubuntu after a while so this should be fixed before doing that. (not sure if it's a bug in trayhost, or my program, testing if it happens with a more simple program...)

**Comment by alex2108** [comment]
Problem with not updating text is now hopefully fixed by changing the tray library used, will test that for some time and if it works I will start working on putting more info in there.

**Comment by kowach** [comment]
This will be great. 
I have another issue, my tray icon constantly shows red arrow (upload). WebGUI says constant 1-2 B/s Upload Rate, but I think that is not the problem. I have device that is in constant _Syncing State_ because I have set ignore patterns that partially sync one folder on first device and same folder fully sync on other. I have searched Syncthing forum and there is sad that this is the way Syncthing works. 

As I can see syncthing-tray reads [completion](https://github.com/alex2108/syncthing-tray/blob/master/main.go#L182) instead upload/download rate?

**Comment by alex2108** [comment]
> As I can see syncthing-tray reads completion instead upload/download rate?

yes it does, it should show the same thing as the GUI. When one remote device has completion<100 it is considered "syncing".

As soon as I have the upload rate in the tooltip it could easily be used to optionally set the icon based on this.

**Comment by kowach** [comment]
But in my case I have folder that never completes (because ignore pattern) - in GUI it looks like stuck on 74% but that is "feature" - annoying thing.
I looked into [Syncthing code](https://github.com/syncthing/syncthing/blob/1a0a8a1655246161783a6ba8312c207458b52e98/gui/default/syncthing/core/syncthingController.js#L463) and they calculate current UL/DL bandwidth from two queries on /rest/system/connections, they calculate `inbps = (inBytesTotal second - inBytesTotal first) / time between queries`.

**Comment by alex2108** [comment]
rates are now shown and can be used to determine upload/download state with command line option `-R`
