### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kowach** [alex2108/syncthing-tray#21]
After few days I noticed my memory is getting low and syncthing-tray was on the top 11GB usage :D 

![Image of Yaktocat](https://i.snag.gy/cVh30O.jpg)

Win10, 64x

I was using parameter -target="http://user:pass@localhost:8080" which apparently stop working on version 0.13. I removed user:pass and added -api="key" paremeter

**Comment by alex2108** [comment]
Just looked at my memory usage and it looks like I can reproduce it as I see a slight increase in memory but never noticed it going to extreme values because I shutdown my computer every day.

looks like you need to restart syncthing-tray from time to time until I found the cause...

**Comment by alex2108** [comment]
Should be fixed in the latest release, if not there is a second leak then I will open it again.
